import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200","300", "400", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={poppins.className}>{children}</body>
  </html>
  );
}
