import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";
import Footer from "@/component/footer/Footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200","300", "400", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Intelisync",
  description: "Generated by Next.js",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={poppins.className}>
      <Navbar />
          {children}
      <Footer />
    </body>
  </html>
  );
}
