export const events = [
  {
    month: "January 2025",
    events: [
      {
        name: "TechLaunch",
        date: "Jan 5 - Jan 6",
        location: "America",
        category: "Technology",
      },
      {
        name: "FinanceHub",
        date: "Jan 8 - Jan 9",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "Healthcare Summit",
        date: "Jan 10 - Jan 11",
        location: "India",
        category: "Healthcare",
      },
      {
        name: "Education Expo",
        date: "Jan 12 - Jan 13",
        location: "Canada",
        category: "Education",
      },
      {
        name: "CyberSecure 2025",
        date: "Jan 15 - Jan 16",
        location: "Germany",
        category: "Technology",
      },
      {
        name: "AI Conference",
        date: "Jan 18 - Jan 19",
        location: "America",
        category: "Technology",
      },
      {
        name: "Financial Insights",
        date: "Jan 20 - Jan 21",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "HealthTech Forum",
        date: "Jan 22 - Jan 23",
        location: "India",
        category: "Healthcare",
      },
      {
        name: "EduTech Meet",
        date: "Jan 25 - Jan 26",
        location: "Canada",
        category: "Education",
      },
      {
        name: "Blockchain World",
        date: "Jan 28 - Jan 29",
        location: "America",
        category: "Finance",
      },
    ],
  },
  {
    month: "February 2025",
    events: [
      {
        name: "FinovateEurope",
        date: "Feb 5 - Feb 6",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "Souk Tech",
        date: "Feb 8 - Feb 9",
        location: "India",
        category: "Technology",
      },
      {
        name: "Health Summit",
        date: "Feb 12 - Feb 13",
        location: "America",
        category: "Healthcare",
      },
      {
        name: "EducationCon",
        date: "Feb 14 - Feb 15",
        location: "Canada",
        category: "Education",
      },
      {
        name: "AI Global Meetup",
        date: "Feb 18 - Feb 19",
        location: "Germany",
        category: "Technology",
      },
      {
        name: "Money Matters",
        date: "Feb 20 - Feb 21",
        location: "America",
        category: "Finance",
      },
      {
        name: "Healthcare Innovation",
        date: "Feb 22 - Feb 23",
        location: "India",
        category: "Healthcare",
      },
      {
        name: "EduNext",
        date: "Feb 24 - Feb 25",
        location: "Canada",
        category: "Education",
      },
      {
        name: "TechWorld 2025",
        date: "Feb 26 - Feb 27",
        location: "Germany",
        category: "Technology",
      },
      {
        name: "Banking Expo",
        date: "Feb 28 - Feb 29",
        location: "America",
        category: "Finance",
      },
    ],
  },
  {
    month: "March 2025",
    events: [
      {
        name: "InnovateTech",
        date: "Mar 1 - Mar 2",
        location: "Canada",
        category: "Technology",
      },
      {
        name: "CryptoCon 2025",
        date: "Mar 3 - Mar 4",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "Medical Insights",
        date: "Mar 6 - Mar 7",
        location: "America",
        category: "Healthcare",
      },
      {
        name: "EduStars",
        date: "Mar 8 - Mar 9",
        location: "India",
        category: "Education",
      },
      {
        name: "AI Revolution",
        date: "Mar 10 - Mar 11",
        location: "Canada",
        category: "Technology",
      },
      {
        name: "Future Finance",
        date: "Mar 12 - Mar 13",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "Wellness Tech",
        date: "Mar 14 - Mar 15",
        location: "America",
        category: "Healthcare",
      },
      {
        name: "EdTech Live",
        date: "Mar 16 - Mar 17",
        location: "India",
        category: "Education",
      },
      {
        name: "CyberSecure Summit",
        date: "Mar 18 - Mar 19",
        location: "Germany",
        category: "Technology",
      },
      {
        name: "FinTech Expo",
        date: "Mar 20 - Mar 21",
        location: "America",
        category: "Finance",
      },
    ],
  },
  {
    month: "April 2025",
    events: [
      {
        name: "NextTech 2025",
        date: "Apr 1 - Apr 2",
        location: "Canada",
        category: "Technology",
      },
      {
        name: "Finance Future",
        date: "Apr 3 - Apr 4",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "Health Forum",
        date: "Apr 6 - Apr 7",
        location: "America",
        category: "Healthcare",
      },
      {
        name: "Learn Expo",
        date: "Apr 8 - Apr 9",
        location: "India",
        category: "Education",
      },
      {
        name: "AI NextGen",
        date: "Apr 10 - Apr 11",
        location: "Canada",
        category: "Technology",
      },
      {
        name: "Banking World",
        date: "Apr 12 - Apr 13",
        location: "Germany",
        category: "Finance",
      },
      {
        name: "Global Health Summit",
        date: "Apr 14 - Apr 15",
        location: "America",
        category: "Healthcare",
      },
      {
        name: "Smart Learning",
        date: "Apr 16 - Apr 17",
        location: "India",
        category: "Education",
      },
      {
        name: "TechFront",
        date: "Apr 18 - Apr 19",
        location: "Canada",
        category: "Technology",
      },
      {
        name: "Money Expo",
        date: "Apr 20 - Apr 21",
        location: "Germany",
        category: "Finance",
      },
    ],
  },
];
